matrix:
  include:
    - language: go
      go_import_path: github.com/athomecomar/athome/backend/users
      go: 1.14.x
      before_script:
        - cd backend/users
      script:
        - make check
    - language: go
      go_import_path: github.com/athomecomar/athome/backend/auth
      go: 1.14.x
      before_script:
        - cd backend/auth
      script:
        - make check


notifications:
  email:
    - dev@athome.com.ar
