version: "3.7"
services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"

  users_db:
    env_file: backend/users/build/db/dev.env
    image: postgres:12
    volumes:
      - users_db:/var/lib/postgresql/data

  users_svc:
    env_file: backend/users/build/svc/dev.env
    build:
      context: backend/users
    ports:
      - "9991:9991"
    volumes:
      - ./backend/users/migrations:/users/migrations
    depends_on:
      - users_db

volumes:
  users_db:
  users_svc:
