version: "3.7"
services:
  users_db:
    env_file: backend/users/build/db/dev.env
    image: postgres:12
    volumes:
      - users_db:/var/lib/postgresql/data

  users_svc:
    env_file: backend/users/build/svc/dev.env
    build:
      context: backend/users
    ports:
      - "9991:9991"
    volumes:
      - ./backend/users/migrations:/users/migrations
    depends_on:
      - users_db

  auth_svc:
    env_file: backend/auth/build/svc/dev.env
    build:
      context: backend/auth
    ports:
      - "9990:9990"
    depends_on:
      - auth_redis

  auth_redis:
    image: redis:4-alpine
    command: redis-server --requirepass redis_pwd
    volumes:
      - auth_redis:/data

volumes:
  users_svc:
  users_db:
  auth_redis:
