version: "3"
services:
  db:
    env_file: ./build/db/dev.env 
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data

  svc:
    env_file: ./build/svc/dev.env 
    build: 
        args:
          env: development
        context: .
    command: go run main.go 
    ports:
      - "9991:9991"
    volumes:
      - .:/user
    environment:
      GRPC_GO_LOG_VERBOSITY_LEVEL: 99
      GRPC_GO_LOG_SEVERITY_LEVEL: info
    depends_on:
      - db   

volumes:
  postgres:
